(() => {
  'use strict';
  const state={csrf:'',route:'dashboard',project:null,memory:null}; const view=document.querySelector('#view'), notice=document.querySelector('#notice');
  const labels={ja:{save:'保存',cancel:'取り消し',delete:'削除',archive:'アーカイブ',loading:'読み込んでいます…'}};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const tell=(m,kind='')=>{notice.className=kind;notice.textContent=m;};
  async function api(path,method='GET',body){const opts={method,headers:{Accept:'application/json'}};if(method!=='GET'){opts.headers['Content-Type']='application/json';opts.headers['X-RouteCraft-CSRF']=state.csrf;opts.body=JSON.stringify(body||{});}const r=await fetch(path,opts);const j=await r.json().catch(()=>({ok:false,error:{message:'応答を読めません'}}));if(!r.ok||!j.ok)throw Error(j.error?.message||'処理に失敗しました');return j.data;}
  const form=(title,fields,submit='保存')=>`<section class="sheet"><h2>${title}</h2><form class="form" data-form="${fields.kind||''}">${fields.html}<div class="actions"><button>${submit}</button><button type="button" data-back>戻る</button></div></form></section>`;
  const types=['decision','failure','lesson','next_action','constraint','architecture','file_reference','dependency','deployment','security','note','session_summary'];
  const options=(items,current)=>items.map(x=>`<option${x===(current||'')?' selected':''}>${esc(x)}</option>`).join('');
  const csv=v=>Array.isArray(v)?v.join(', '):(v||'');
  function memoryForm(value={}){return form(value.id?'記憶を編集':'記憶を追加',{kind:'memory',html:`<input type="hidden" name="id" value="${esc(value.id)}">${value.id?'':`<label>プロジェクトID<input required name="project_id" value="${esc(state.project?.id||'')}"></label>`}<label>題名<input required name="title" value="${esc(value.title)}"></label><label>種別<select name="type">${options(types,value.memory_type||value.type||'note')}</select></label><label>重要度<select name="importance">${options(['high','medium','low'],value.importance||'medium')}</select></label><label>タグ（カンマ区切り）<input name="tags" value="${esc(csv(value.tags))}"></label><label>関連ファイル（カンマ区切り）<input name="related_files" value="${esc(csv(value.related_files))}"></label><label>関連コミット（カンマ区切り）<input name="related_commits" value="${esc(csv(value.related_commits))}"></label><label>情報源<input name="source" value="${esc(value.source||'ui')}"></label><label>内容<textarea required name="content" rows="8">${esc(value.content||value.body)}</textarea></label><label class="check"><input type="checkbox" name="verified" ${value.verified?'checked':''}>検証済み</label><label class="check"><input type="checkbox" name="active" ${value.active!==false?'checked':''}>有効</label>`});}
  function projectForm(value={}){return form(value.id?'プロジェクトを編集':'プロジェクトを追加',{kind:'project',html:`<input type="hidden" name="id" value="${esc(value.id)}"><label>プロジェクト名<input required name="name" value="${esc(value.name)}"></label><label>説明<textarea name="description" rows="4">${esc(value.description)}</textarea></label><label>現在の目的<textarea name="current_objective" rows="4">${esc(value.current_objective)}</textarea></label><label>リポジトリパス（任意）<input name="repo_path" value="${esc(value.repo_path||value.path)}"></label><label>Git remote URL（任意）<input name="git_remote_url" value="${esc(value.git_remote_url)}"></label><label>AI agents（カンマ区切り）<input name="ai_agents" value="${esc(csv(value.ai_agents))}"></label><label>言語（カンマ区切り）<input name="languages" value="${esc(csv(value.languages))}"></label><label>タグ（カンマ区切り）<input name="tags" value="${esc(csv(value.tags))}"></label>`});}
  async function dashboard(){const d=await api('/api/dashboard');return `<section class="intro"><p class="eyebrow">OVERVIEW</p><h2>今日の作業を、次へ渡せる形に。</h2><p>記録、プロジェクト、引き継ぎをこのPCの中で管理します。</p></section><dl class="facts">${Object.entries(d||{}).slice(0,6).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(typeof v==='object'?JSON.stringify(v):v)}</dd></div>`).join('')}</dl><section class="sheet"><h2>はじめる</h2><p><button data-route="projects">プロジェクトを追加</button> <button data-route="memories">記憶を記録</button></p></section>`;}
  async function projects(){const d=await api('/api/projects');const rows=Array.isArray(d)?d:(d.items||[]);return `<section class="heading"><div><p class="eyebrow">PROJECTS</p><h2>プロジェクト</h2></div><div class="actions"><button data-new="project">追加</button><button data-package-import>パッケージを読み込む</button></div></section>${rows.length?`<ul class="list">${rows.map(x=>`<li><a href="#project/${encodeURIComponent(x.id)}"><strong>${esc(x.name||x.title||x.id)}</strong><span>${esc(x.description||x.status||'詳細を開く')}</span></a></li>`).join('')}</ul>`:'<p class="empty">まだプロジェクトがありません。</p>'}`;}
  async function project(id){const p=await api('/api/projects/'+encodeURIComponent(id));state.project=p;return `<section class="heading"><div><p class="eyebrow">PROJECT</p><h2>${esc(p.name||p.title||id)}</h2><p>${esc(p.description||'説明はまだありません。')}</p></div><div class="actions"><button data-edit-project>編集</button><button data-archive-project>アーカイブ</button><button class="danger" data-delete-project>削除</button></div></section><section class="sheet"><h3>このプロジェクトの操作</h3><p><button data-pack="context">Context Pack</button> <button data-pack="handoff">Handoff Pack</button> <button data-package-export>プロジェクトパッケージを出力</button> <button data-git>Git 状態</button></p><pre id="detail">${esc(JSON.stringify(p,null,2))}</pre></section>`;}
  async function memories(){const d=await api('/api/memories');const rows=Array.isArray(d)?d:(d.items||[]);return `<section class="heading"><div><p class="eyebrow">MEMORIES</p><h2>記憶</h2></div><button data-new="memory">追加</button></section><form id="search" class="search"><label>検索<input name="query" placeholder="判断、失敗、プロジェクト名…"></label><label>プロジェクトID<input name="project_id" value="${esc(state.project?.id||'')}"></label><label>種別<select name="type"><option value="">指定なし</option>${options(types)}</select></label><label>タグ<input name="tags" placeholder="タグ"></label><label>重要度<select name="importance"><option value="">指定なし</option>${options(['high','medium','low'])}</select></label><label>有効<select name="active"><option value="">指定なし</option><option value="true">はい</option><option value="false">いいえ</option></select></label><label>検証済み<select name="verified"><option value="">指定なし</option><option value="true">はい</option><option value="false">いいえ</option></select></label><button>検索</button></form><div id="memoryRows">${memoryRows(rows)}</div>`;}
  const memoryRows=rows=>rows.length?`<ul class="list">${rows.map(x=>`<li><button class="row" data-memory="${esc(x.id)}"><strong>${esc(x.title||x.id)}</strong><span>${esc(x.memory_type||x.type||'note')} / ${esc(x.importance||'')}</span></button></li>`).join('')}</ul>`:'<p class="empty">条件に合う記憶はありません。</p>';
  async function memory(id){const m=await api('/api/memories/'+encodeURIComponent(id));state.memory=m;return `<section class="heading"><div><p class="eyebrow">MEMORY</p><h2>${esc(m.title||id)}</h2><p>${esc(m.memory_type||m.type)} / ${esc(m.importance)}</p></div><div class="actions"><button data-edit-memory>編集</button><button class="danger" data-delete-memory>削除</button></div></section><section class="sheet"><pre>${esc(m.body||m.content||'')}</pre></section>`;}
  async function packs(){return `<section class="heading"><div><p class="eyebrow">PACKS</p><h2>Context / Handoff Pack</h2><p>必要な情報だけを選んで、共有前に内容を確認します。</p></div></section><section class="sheet"><form id="pack"><label>プロジェクトID<input name="project_id" value="${esc(state.project?.id||'')}"></label><label>プロフィール<select name="profile"><option>compact</option><option selected>standard</option><option>full</option></select></label><div class="actions"><button name="kind" value="context">Context Packを作成</button><button name="kind" value="handoff">Handoff Packを作成</button></div></form><pre id="packOut">未作成</pre></section>`;}
  async function backup(){const d=await api('/api/backups');const rows=Array.isArray(d)?d:(d.items||[]);return `<section class="heading"><div><p class="eyebrow">SAFEKEEPING</p><h2>保管と復元</h2></div><button data-backup>バックアップを作成</button></section><section class="sheet"><h3>バックアップ一覧</h3>${rows.length?`<ul class="list">${rows.map(x=>`<li><button class="row" data-select-backup="${esc(x.path)}"><strong>${esc(x.name)}</strong><span>${esc(x.path)}</span></button></li>`).join('')}</ul>`:'<p class="empty">バックアップはまだありません。</p>'}<form id="restore"><label>復元するアーカイブパス<input required name="backup_id"></label><label>確認のため RESTORE と入力<input required name="confirm" autocomplete="off"></label><button class="danger">復元する</button></form></section>`;}
  async function settings(){const d=await api('/api/settings');return form('設定',{kind:'settings',html:`<label>設定JSON<textarea required name="json" rows="12">${esc(JSON.stringify(d,null,2))}</textarea></label>`});}
  async function doctor(){const d=await api('/api/doctor');return `<section class="heading"><div><p class="eyebrow">SYSTEM</p><h2>システム診断</h2></div><button data-doctor>再確認</button></section><pre class="diagnostic">${esc(JSON.stringify(d,null,2))}</pre>`;}
  async function render(){const hash=location.hash.slice(1)||'dashboard';state.route=hash;try{const [base,id]=hash.split('/');view.innerHTML=base==='dashboard'?await dashboard():base==='projects'?await projects():base==='project'?await project(decodeURIComponent(id)):base==='memories'?await memories():base==='memory'?await memory(decodeURIComponent(id)):base==='packs'?await packs():base==='backup'?await backup():base==='settings'?await settings():await doctor();tell('');}catch(e){view.innerHTML=`<section class="error"><h2>表示できませんでした</h2><p>${esc(e.message)}</p><button data-route="dashboard">概要へ戻る</button></section>`;tell(e.message,'error');}}
  function values(f){return Object.fromEntries(new FormData(f).entries());}
  const list=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
  function cleanSearch(data){const out={};for(const [key,value] of Object.entries(data)){if(value==='')continue;out[key]=value;}for(const key of ['tags'])if(out[key])out[key]=list(out[key]);for(const key of ['active','verified'])if(key in out)out[key]=out[key]==='true';return out;}
  document.addEventListener('click',async e=>{
    const b=e.target.closest('button,[data-route]');
    if(!b)return;
    if(b.dataset.route){location.hash=b.dataset.route;return;}
    if('back' in b.dataset){history.back();return;}
    try{
      if(b.dataset.new){view.innerHTML=b.dataset.new==='project'?projectForm():memoryForm();return;}
      if(b.dataset.memory){location.hash='memory/'+encodeURIComponent(b.dataset.memory);return;}
      if('editMemory' in b.dataset){view.innerHTML=memoryForm(state.memory);return;}
      if('deleteMemory' in b.dataset){const c=prompt(`削除するにはID「${state.memory.id}」を正確に入力してください`);await api('/api/memories/'+encodeURIComponent(state.memory.id),'DELETE',{confirm:c});location.hash='memories';return;}
      if('editProject' in b.dataset){view.innerHTML=projectForm(state.project);return;}
      if('archiveProject' in b.dataset){await api('/api/projects/'+encodeURIComponent(state.project.id)+'/archive','POST',{});tell('アーカイブしました');location.hash='projects';return;}
      if('deleteProject' in b.dataset){const c=prompt(`削除するにはID「${state.project.id}」を正確に入力してください`);await api('/api/projects/'+encodeURIComponent(state.project.id),'DELETE',{confirm:c});location.hash='projects';return;}
      if('packageExport' in b.dataset){const output=prompt('出力先のローカルパス（既存ファイルは上書きしません）');if(!output)return;const d=await api('/api/projects/'+encodeURIComponent(state.project.id)+'/package','POST',{action:'export',output,as_zip:true});document.querySelector('#detail').textContent=`出力しました: ${d.output}`;return;}
      if('packageImport' in b.dataset){const path=prompt('読み込むプロジェクトパッケージのローカルパス');if(!path)return;const d=await api('/api/project-package/import','POST',{path,conflict:'detect'});tell(d.imported===false?'既存プロジェクトとの競合を記録しました':`読み込みました: ${d.project_id||''}`);await render();return;}
      if(b.dataset.pack){const d=await api('/api/'+b.dataset.pack,'POST',{project_id:state.project?.id});document.querySelector('#detail').textContent=b.dataset.pack==='context'?d.content:`生成先: ${d.folder}${d.zip?`\nZIP: ${d.zip}`:''}\n\n${JSON.stringify(d,null,2)}`;return;}
      if('git' in b.dataset){const d=await api('/api/git','POST',{project_id:state.project?.id});document.querySelector('#detail').textContent=JSON.stringify(d,null,2);return;}
      if(b.dataset.selectBackup){const input=document.querySelector('#restore [name=backup_id]');if(input){input.value=b.dataset.selectBackup;input.focus();}return;}
      if('backup' in b.dataset){const d=await api('/api/backups','POST',{});await render();tell(`バックアップを作成しました: ${d.output}`);return;}
      if('doctor' in b.dataset){await render();}
    }catch(err){tell(err.message,'error');}
  });
  document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target, data=values(f);try{
    if(f.dataset.form==='project'){const id=data.id;delete data.id;for(const key of ['ai_agents','languages','tags'])data[key]=list(data[key]);await api(id?'/api/projects/'+encodeURIComponent(id):'/api/projects',id?'PATCH':'POST',data);location.hash='projects';}
    else if(f.dataset.form==='memory'){const id=data.id;delete data.id;for(const key of ['tags','related_files','related_commits'])data[key]=list(data[key]);data.verified=f.querySelector('[name=verified]').checked;data.active=f.querySelector('[name=active]').checked;await api(id?'/api/memories/'+encodeURIComponent(id):'/api/memories',id?'PATCH':'POST',data);location.hash=id?'memory/'+encodeURIComponent(id):'memories';}
    else if(f.dataset.form==='settings'){await api('/api/settings','PATCH',JSON.parse(data.json));tell('設定を保存しました');}
    else if(f.id==='search'){const d=await api('/api/memories/search','POST',cleanSearch(data));document.querySelector('#memoryRows').innerHTML=memoryRows(Array.isArray(d)?d:(d.items||[]));}
    else if(f.id==='pack'){const d=await api('/api/'+e.submitter.value,'POST',data);document.querySelector('#packOut').textContent=e.submitter.value==='context'?d.content:`生成先: ${d.folder}${d.zip?`\nZIP: ${d.zip}`:''}\n\n${JSON.stringify(d,null,2)}`;}
    else if(f.id==='restore'){const d=await api('/api/restore','POST',data);const warnings=Array.isArray(d.warnings)?d.warnings:[];tell(warnings.length?`復元しました。警告: ${warnings.join(', ')}${d.retained_rollback?` / 保持されたrollback: ${d.retained_rollback}`:''}`:'復元しました',warnings.length?'warning':'');}
  }catch(err){tell(err.message,'error');}});
  document.querySelector('#navToggle').addEventListener('click',e=>{const on=document.body.classList.toggle('nav-open');e.currentTarget.setAttribute('aria-expanded',String(on));});
  document.querySelector('#nav').addEventListener('click',e=>{if(e.target.closest('a')){document.body.classList.remove('nav-open');document.querySelector('#navToggle').setAttribute('aria-expanded','false');}});
  (async()=>{try{state.csrf=(await api('/api/bootstrap')).csrf_token;await render();}catch(e){tell('初期化できません: '+e.message,'error');}})();window.addEventListener('hashchange',render);
})();
